### ISSUE TITLE
bay cannot run when it does not recognize a running container

### ISSUE THREAD

**Issue by eyalr** [eventbrite/bay#94]
If there is a running container whose configuration disappears, bay errors and no commands can be run. You get an error message with the form of:

`bay.exceptions.DockerRuntimeError: Cannot find local container for running container eventbrite.core-daemons.1`

This case should be handled more gracefully, letting you run commands and perhaps prompting you to shut down the running unknown container.

**Comment by andrewgodwin** [comment]
Can you file a mirror of this in our internal tracker too? We don't regularly look at this one yet.
